/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NutrisiRouteImport } from './routes/nutrisi'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspirasiIdRouteImport } from './routes/inspirasi.$id'
import { Route as FlashcardIdRouteImport } from './routes/flashcard.$id'
import { Route as AuthenticatedBerandaRouteImport } from './routes/_authenticated/beranda'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrisiRoute = NutrisiRouteImport.update({
  id: '/nutrisi',
  path: '/nutrisi',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirasiIdRoute = InspirasiIdRouteImport.update({
  id: '/inspirasi/$id',
  path: '/inspirasi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardIdRoute = FlashcardIdRouteImport.update({
  id: '/flashcard/$id',
  path: '/flashcard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBerandaRoute = AuthenticatedBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/_authenticated/beranda': typeof AuthenticatedBerandaRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/beranda'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/beranda'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/_authenticated/beranda'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CopilotRoute: typeof CopilotRoute
  NutrisiRoute: typeof NutrisiRoute
  ProfilRoute: typeof ProfilRoute
  FlashcardIdRoute: typeof FlashcardIdRoute
  InspirasiIdRoute: typeof InspirasiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrisi': {
      id: '/nutrisi'
      path: '/nutrisi'
      fullPath: '/nutrisi'
      preLoaderRoute: typeof NutrisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirasi/$id': {
      id: '/inspirasi/$id'
      path: '/inspirasi/$id'
      fullPath: '/inspirasi/$id'
      preLoaderRoute: typeof InspirasiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard/$id': {
      id: '/flashcard/$id'
      path: '/flashcard/$id'
      fullPath: '/flashcard/$id'
      preLoaderRoute: typeof FlashcardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/beranda': {
      id: '/_authenticated/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AuthenticatedBerandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBerandaRoute: typeof AuthenticatedBerandaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBerandaRoute: AuthenticatedBerandaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CopilotRoute: CopilotRoute,
  NutrisiRoute: NutrisiRoute,
  ProfilRoute: ProfilRoute,
  FlashcardIdRoute: FlashcardIdRoute,
  InspirasiIdRoute: InspirasiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
