/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KIdRouteImport } from './routes/k.$id'
import { Route as InspirasiIdRouteImport } from './routes/inspirasi.$id'
import { Route as FlashcardIdRouteImport } from './routes/flashcard.$id'
import { Route as AuthenticatedNutrisiRouteImport } from './routes/_authenticated/nutrisi'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'
import { Route as AuthenticatedBerandaRouteImport } from './routes/_authenticated/beranda'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KIdRoute = KIdRouteImport.update({
  id: '/k/$id',
  path: '/k/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirasiIdRoute = InspirasiIdRouteImport.update({
  id: '/inspirasi/$id',
  path: '/inspirasi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardIdRoute = FlashcardIdRouteImport.update({
  id: '/flashcard/$id',
  path: '/flashcard/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNutrisiRoute = AuthenticatedNutrisiRouteImport.update({
  id: '/nutrisi',
  path: '/nutrisi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerandaRoute = AuthenticatedBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/nutrisi': typeof AuthenticatedNutrisiRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
  '/k/$id': typeof KIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/nutrisi': typeof AuthenticatedNutrisiRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
  '/k/$id': typeof KIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/profil': typeof ProfilRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/beranda': typeof AuthenticatedBerandaRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/nutrisi': typeof AuthenticatedNutrisiRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
  '/k/$id': typeof KIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/profil'
    | '/tentang'
    | '/beranda'
    | '/copilot'
    | '/nutrisi'
    | '/flashcard/$id'
    | '/inspirasi/$id'
    | '/k/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/profil'
    | '/tentang'
    | '/beranda'
    | '/copilot'
    | '/nutrisi'
    | '/flashcard/$id'
    | '/inspirasi/$id'
    | '/k/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/profil'
    | '/tentang'
    | '/_authenticated/beranda'
    | '/_authenticated/copilot'
    | '/_authenticated/nutrisi'
    | '/flashcard/$id'
    | '/inspirasi/$id'
    | '/k/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProfilRoute: typeof ProfilRoute
  TentangRoute: typeof TentangRoute
  FlashcardIdRoute: typeof FlashcardIdRoute
  InspirasiIdRoute: typeof InspirasiIdRoute
  KIdRoute: typeof KIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$id': {
      id: '/k/$id'
      path: '/k/$id'
      fullPath: '/k/$id'
      preLoaderRoute: typeof KIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirasi/$id': {
      id: '/inspirasi/$id'
      path: '/inspirasi/$id'
      fullPath: '/inspirasi/$id'
      preLoaderRoute: typeof InspirasiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard/$id': {
      id: '/flashcard/$id'
      path: '/flashcard/$id'
      fullPath: '/flashcard/$id'
      preLoaderRoute: typeof FlashcardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nutrisi': {
      id: '/_authenticated/nutrisi'
      path: '/nutrisi'
      fullPath: '/nutrisi'
      preLoaderRoute: typeof AuthenticatedNutrisiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beranda': {
      id: '/_authenticated/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AuthenticatedBerandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBerandaRoute: typeof AuthenticatedBerandaRoute
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedNutrisiRoute: typeof AuthenticatedNutrisiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBerandaRoute: AuthenticatedBerandaRoute,
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedNutrisiRoute: AuthenticatedNutrisiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProfilRoute: ProfilRoute,
  TentangRoute: TentangRoute,
  FlashcardIdRoute: FlashcardIdRoute,
  InspirasiIdRoute: InspirasiIdRoute,
  KIdRoute: KIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
