/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NutrisiRouteImport } from './routes/nutrisi'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as BerandaRouteImport } from './routes/beranda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspirasiIdRouteImport } from './routes/inspirasi.$id'
import { Route as FlashcardIdRouteImport } from './routes/flashcard.$id'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NutrisiRoute = NutrisiRouteImport.update({
  id: '/nutrisi',
  path: '/nutrisi',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const BerandaRoute = BerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspirasiIdRoute = InspirasiIdRouteImport.update({
  id: '/inspirasi/$id',
  path: '/inspirasi/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardIdRoute = FlashcardIdRouteImport.update({
  id: '/flashcard/$id',
  path: '/flashcard/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beranda': typeof BerandaRoute
  '/copilot': typeof CopilotRoute
  '/nutrisi': typeof NutrisiRoute
  '/profil': typeof ProfilRoute
  '/flashcard/$id': typeof FlashcardIdRoute
  '/inspirasi/$id': typeof InspirasiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beranda'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beranda'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  id:
    | '__root__'
    | '/'
    | '/beranda'
    | '/copilot'
    | '/nutrisi'
    | '/profil'
    | '/flashcard/$id'
    | '/inspirasi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BerandaRoute: typeof BerandaRoute
  CopilotRoute: typeof CopilotRoute
  NutrisiRoute: typeof NutrisiRoute
  ProfilRoute: typeof ProfilRoute
  FlashcardIdRoute: typeof FlashcardIdRoute
  InspirasiIdRoute: typeof InspirasiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrisi': {
      id: '/nutrisi'
      path: '/nutrisi'
      fullPath: '/nutrisi'
      preLoaderRoute: typeof NutrisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beranda': {
      id: '/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof BerandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspirasi/$id': {
      id: '/inspirasi/$id'
      path: '/inspirasi/$id'
      fullPath: '/inspirasi/$id'
      preLoaderRoute: typeof InspirasiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard/$id': {
      id: '/flashcard/$id'
      path: '/flashcard/$id'
      fullPath: '/flashcard/$id'
      preLoaderRoute: typeof FlashcardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BerandaRoute: BerandaRoute,
  CopilotRoute: CopilotRoute,
  NutrisiRoute: NutrisiRoute,
  ProfilRoute: ProfilRoute,
  FlashcardIdRoute: FlashcardIdRoute,
  InspirasiIdRoute: InspirasiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
